# version: '3'

# services:
#   db:   
#     image: mysql:5.6.50
#     command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
#     ports: 
#       - '3306:3306'
#     volumes:
#       - mysql-data:/var/lib/mysql 
#     environment:
#       MYSQL_DATABASE: tiritsumo_development   
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_USER: root
#       MYSQL_PASSWORD: password

#   web:  
#     build:
#       context: .
#       dockerfile: Dockerfile
#     command: bundle exec rails s -p 3000 -b '0.0.0.0'
#     tty: true 
#     stdin_open: true
#     depends_on:
#       - db
#     ports:
#       - "3000:3000"
#     volumes:
#       - .:/tiritsumo
# volumes:      
#   mysql-data:

version: '3' #docker-composeのバージョン
services:
  db:
    image: mysql:5.6.50 #既存アプリとあわせる。ターミナルに[$ mysql --version]で確認
    environment:
      MYSQL_ROOT_PASSWORD: password #あなたのパスワード
      MYSQL_DATABASE: root
    ports:
      - "4306:3306"
    volumes:
      - mysql-data:/var/lib/mysql 
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/tiritsumo
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  mysql-data: