version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5
    working_directory: ~/tiritsumo
    steps:
      - checkout:
          path: ~/tiritsumo
      - ruby/install-deps

  test:
    docker:
      - image: circleci/ruby:2.6.5
      - image: circleci/mysql:5.6.51
        environment:
          MYSQL_ROOT_PASSWORD: password 
          MYSQL_DATABASE:  tiritsumo_test
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      MYSQL_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/tiritsumo        
    steps:
      - checkout:
          path: ~/tiritsumo
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: test
          command: bundle exec rake test     


  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - 1c:19:93:88:c5:9e:c0:2f:d4:60:1e:c6:4d:4e:96:44
      - deploy:
          name: Capistrano deploy
          command: bundle exec cap production deploy



workflows:
  version: 2.1
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master