version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    working_directory: ~/tiritsumo
    # executor: ruby/default
    steps:
      - checkout
        path: ~/tiritsumo
      # - run:
      #     name: Which bundler?
      #     command: bundle -v
      - ruby/install-deps

  test:
    docker:
      - image: circleci/ruby:2.7
      - image: circleci/mysql:5.5
        environment:
          MYSQL_ROOT_PASSWORD: 
          MYSQL_DATABASE: tiritsumo_test
          MYSQL_USER: root
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      MYSQL_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/tiritsumo        
    steps:
      - checkout:
          path: ~/tiritsumo
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: test
          command: bundle exec rake test     




workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main